# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerclock', '0003_tournament_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='knockout_bool',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='name',
        ),
        migrations.AddField(
            model_name='tournament',
            name='knockout_type',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_names',
            field=models.CharField(default='', max_length=200),
        ),
    ]
